### PR TITLE
Milestone 2 features

### PR DESCRIPTION
**Pull request by warblo001**
In this milestone, I created a model with associations and all requested features for friendships.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

## Hello @warblo001, good job so far :clap:  your models file looks fine. Good job :+1:. But before we can consider this millstone completed please implement the following requirements :arrow_down: 

- [x] I get the following error when I try to go to the users index page: Screenshot from 2021-04-20 19-14-17
- [x] Also keep in mind that the user should be able to: invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))  **&&**  see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) **&&** 
can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) **AND** User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] I also get the following error when I go to the users show page:  Screenshot from 2021-04-20 19-19-52
- [x] Keep in mind that: There is should be a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Please add rspec **Unit and Integration tests!** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))


_Please implement all the above mentioned requirements and ask for another code review whenver you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

# HAPPY CODING :computer: :desktop_computer:

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi Alan!
Great job so far:clap::clap:. However, there are still some changes we need to make to get this milestone approved:muscle:.**

**To improve**

- [x] User can invite friends ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Can't find any button to invite friends. Kindly fix this
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Can't see any frienship request. Kindly fix this.
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Kindly also fix this.
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also implement this feature.
- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also fix this.
- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, the post timeline displays posts written by every registered users. Instead of their friends.
- [x] Currently, the tests only cover `model` features. We also need to write tests for features in the controller. Both unit and integration tests that cover positive and negative case scenarios.

**Optional** 

- [x] Just a hint. Recheck your migrations and try to fix any abnormalities.


Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
-------------
Hello @warblo001, you are doing a great project. :clap: :1st_place_medal: Good job working on the required changes. :muscle: 
However, there are a few changes to make to complete this milestone :hammer_and_wrench:  see them below :eyes: :point_down: 
-------------
- [x] I can still see the post from users that are not my friends. Please fix this. 

user_can_see_invite_buttton

- [x] When I run rspec I got 5 failures. Plese fix this

Screenshot from 2021-04-22 11-21-54
------------
Make these required changes :hammer_and_wrench: and send it again for another review. 
Reachme on SLACK if you have any questions about the review. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!!!

MB5W4D

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Alan Solis Paniagua** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [x] After the friendship request is accepted, the logged-in user should be able to see, in the timeline, the posts from its new friend.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
Nice work making the requested changes. 
A user can now see only posts by their friends.
Merge and proceed to the next project.

### Martin Afani
#### Slack: whiz25

**Pull request merged**
